### ISSUE TITLE
Table structure diff - decimal field merge failure

### ISSUE THREAD

**Issue by semenenkov** [KS-DB-Merge-Tools/Issues#9]
Couple of unknown error reports from Aug 10, 2024
Stack trace from the error log:

Application.Current.DispatcherUnhandledException
System.Runtime.InteropServices.COMException (0x80004005): Invalid precision for decimal data type.
   at ADODB.ConnectionClass.Execute(String CommandText, Object& RecordsAffected, Int32 Options)
   at AccdbMerge.Data.Project.⁭⁬‪⁫⁭‏⁭‮⁬‎‫‍‏⁭⁮‪‏‫⁬‍⁫‬​⁮‬‭⁬‍‪‫‫‬⁭‫⁯‍‭‍‌⁮‮(_Connection , String , Object& , Int32 )
   at AccdbMerge.Data.Project.​‫⁮⁬‪‏‍⁯‎⁪‫​‭‍⁭⁮‪⁪⁭‫‏‪‫‮​⁪⁭‮‍‏‬⁭⁭‭‮‪‏‍‫⁭‮(⁮⁯⁪⁮⁯⁭⁪⁪‮‫‫‏​​⁪‪⁫‭⁫⁪⁬⁪⁫‫‍‭⁮‌‭​⁪‍​⁯⁮⁭⁬​‭⁫‮ , Table , Table , TableDef , Connection , Fields , List`1& , String , String )
   at AccdbMerge.Data.Project.‮⁮⁮‬​‏‪‫⁪⁯‫​‍⁭⁪‮⁯​⁬⁪⁪‫‭‏‮‏⁯​⁬⁪‍⁪‭‭​‮‍‍‮‏‮(⁮⁯⁪⁮⁯⁭⁪⁪‮‫‫‏​​⁪‪⁫‭⁫⁪⁬⁪⁫‫‍‭⁮‌‭​⁪‍​⁯⁮⁭⁬​‭⁫‮ , Table , Table , Dictionary`2 , List`1 , TableDef , Connection , Application , List`1 , List`1 , List`1 )
   at AccdbMerge.Data.Project.⁪‮⁬⁯‫⁪‮‮‮​​‬⁭⁪‫‪⁮‮‮‍‪⁯‮⁫‏‪​⁮‌​‏‪⁫⁬‏‏‭⁭⁭‪‮(Project , String , LinkedDef , Dictionary`2 , List`1 , List`1 , List`1 , List`1 , ⁮⁯⁪⁮⁯⁭⁪⁪‮‫‫‏​​⁪‪⁫‭⁫⁪⁬⁪⁫‫‍‭⁮‌‭​⁪‍​⁯⁮⁭⁬​‭⁫‮ , Application )
   at AccdbMerge.ViewModel.TableStructureDiffTab.DoMerge(Boolean mergeToRight)

**Comment by semenenkov** [comment]
It would be great if someone could provide file samples to reproduce this issue
